### ISSUE TITLE
Unable to execute wget -C https://vidsitu-objects.s3.amazonaws.com/vsitu_objs.tar

### ISSUE THREAD

**Issue by zhufq00** [Shinetism/VStates#1]
I would like to ask if there is any way to download vsitu_objs.tar.

Also, I found that some of the videos are no longer downloadable while downloading the video data. Is there any way to resolve the issues related to the dataset?

I really want to replicate this great paper, and I appreciate any help you can provide.

**Comment by guang-yng** [comment]
We have provided new downloading links in data/DATA_PREP.md. You can download vsitu_objs.tar and all available videos with the links.
